---
# tasks file for dhcp-client

# Get name of 2nd ethernet device
- name: Get name of 2nd ethernet interface from shell
  changed_when: false
  ansible.builtin.shell: "networkctl list | sed -n '4'p | awk '{print$2}'"
  register: shell_out

# - debug: msg="{{ shell_out.stdout }}"

- name: Setting fact
  ansible.builtin.set_fact:
    eth_device: "{{ shell_out.stdout }}"

- name: Remove /etc/network/interfaces
  ansible.builtin.file:
    path: /etc/network/interfaces
    state: absent

- name: Copy DHCP config for clients [ethX]
  ansible.builtin.copy:
    src: 01-dhcp-eth.network
    dest: /etc/systemd/network/01-dhcp-eth.network
    mode: '0644'
  when: "'eth' in eth_device"
  notify:
    - Restart systemd-networkd

- name: Copy DHCP config for clients [enp0sX]
  ansible.builtin.copy:
    src: 01-dhcp-enp.network
    dest: /etc/systemd/network/01-dhcp-enp.network
    mode: '0644'
  when: "'enp' in eth_device"
  notify:
    - Restart systemd-networkd

- name: Make sure "systemd-networkd" is enabled
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
