---
# tasks file for dhcp-client

# Get name of 2nd ethernet device
- name: Get name of 2nd ethernet interface from shell
  changed_when: false
  ansible.builtin.shell: "networkctl list | sed -n '4'p | awk '{print$2}'"
  register: shell_out

# - debug: msg="{{ shell_out.stdout }}"

- name: Setting fact
  ansible.builtin.set_fact:
    eth_device: "{{ shell_out.stdout }}"

- name: Take care about /etc/network/interfaces on Debian
  block:

    - name: Get '/etc/network/interfaces' file stat
      ansible.builtin.stat:
        path: /etc/network/interfaces
      register: interfaces_file

    - name: Copy /etc/network/interfaces
      ansible.builtin.copy:
        src: interfaces
        dest: /etc/network/interfaces
        mode: '0644'
        backup: yes
      when: interfaces_file.stat.exists

  when: ansible_distribution == 'Debian'

- name: Copy interface config for DHCP clients
  ansible.builtin.template:
    src: 01-dhcp.network.j2
    dest: /etc/systemd/network/01-dhcp.network
    mode: '0644'
  notify:
    - Restart systemd-networkd

# - name: Copy DHCP config for clients [ethX]
#   ansible.builtin.copy:
#     src: 01-dhcp-eth.network
#     dest: /etc/systemd/network/01-dhcp-eth.network
#     mode: '0644'
#   when: "'eth' in eth_device"
#   notify:
#     - Restart systemd-networkd

# - name: Copy DHCP config for clients [enp0sX]
#   ansible.builtin.copy:
#     src: 01-dhcp-enp.network
#     dest: /etc/systemd/network/01-dhcp-enp.network
#     mode: '0644'
#   when: "'enp' in eth_device"
#   notify:
#     - Restart systemd-networkd

- name: Make sure "systemd-networkd" is enabled
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
